# Generated by Django 5.1.3 on 2025-04-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='is_expired',
            new_name='has_expiry',
        ),
    ]
